// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: biometric.proto

package biometricpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BiometricService_VerifyPunch_FullMethodName   = "/openpresence.biometric.v1.BiometricService/VerifyPunch"
	BiometricService_EnrollFace_FullMethodName    = "/openpresence.biometric.v1.BiometricService/EnrollFace"
	BiometricService_DeleteProfile_FullMethodName = "/openpresence.biometric.v1.BiometricService/DeleteProfile"
)

// BiometricServiceClient is the client API for BiometricService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BiometricServiceClient interface {
	VerifyPunch(ctx context.Context, in *VerifyPunchRequest, opts ...grpc.CallOption) (*VerifyPunchResponse, error)
	EnrollFace(ctx context.Context, in *EnrollFaceRequest, opts ...grpc.CallOption) (*EnrollFaceResponse, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error)
}

type biometricServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBiometricServiceClient(cc grpc.ClientConnInterface) BiometricServiceClient {
	return &biometricServiceClient{cc}
}

func (c *biometricServiceClient) VerifyPunch(ctx context.Context, in *VerifyPunchRequest, opts ...grpc.CallOption) (*VerifyPunchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPunchResponse)
	err := c.cc.Invoke(ctx, BiometricService_VerifyPunch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biometricServiceClient) EnrollFace(ctx context.Context, in *EnrollFaceRequest, opts ...grpc.CallOption) (*EnrollFaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollFaceResponse)
	err := c.cc.Invoke(ctx, BiometricService_EnrollFace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biometricServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProfileResponse)
	err := c.cc.Invoke(ctx, BiometricService_DeleteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BiometricServiceServer is the server API for BiometricService service.
// All implementations must embed UnimplementedBiometricServiceServer
// for forward compatibility.
type BiometricServiceServer interface {
	VerifyPunch(context.Context, *VerifyPunchRequest) (*VerifyPunchResponse, error)
	EnrollFace(context.Context, *EnrollFaceRequest) (*EnrollFaceResponse, error)
	DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error)
	mustEmbedUnimplementedBiometricServiceServer()
}

// UnimplementedBiometricServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBiometricServiceServer struct{}

func (UnimplementedBiometricServiceServer) VerifyPunch(context.Context, *VerifyPunchRequest) (*VerifyPunchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPunch not implemented")
}
func (UnimplementedBiometricServiceServer) EnrollFace(context.Context, *EnrollFaceRequest) (*EnrollFaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollFace not implemented")
}
func (UnimplementedBiometricServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedBiometricServiceServer) mustEmbedUnimplementedBiometricServiceServer() {}
func (UnimplementedBiometricServiceServer) testEmbeddedByValue()                          {}

// UnsafeBiometricServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BiometricServiceServer will
// result in compilation errors.
type UnsafeBiometricServiceServer interface {
	mustEmbedUnimplementedBiometricServiceServer()
}

func RegisterBiometricServiceServer(s grpc.ServiceRegistrar, srv BiometricServiceServer) {
	// If the following call panics, it indicates UnimplementedBiometricServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BiometricService_ServiceDesc, srv)
}

func _BiometricService_VerifyPunch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiometricServiceServer).VerifyPunch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BiometricService_VerifyPunch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiometricServiceServer).VerifyPunch(ctx, req.(*VerifyPunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiometricService_EnrollFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollFaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiometricServiceServer).EnrollFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BiometricService_EnrollFace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiometricServiceServer).EnrollFace(ctx, req.(*EnrollFaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiometricService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiometricServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BiometricService_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiometricServiceServer).DeleteProfile(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BiometricService_ServiceDesc is the grpc.ServiceDesc for BiometricService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BiometricService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openpresence.biometric.v1.BiometricService",
	HandlerType: (*BiometricServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyPunch",
			Handler:    _BiometricService_VerifyPunch_Handler,
		},
		{
			MethodName: "EnrollFace",
			Handler:    _BiometricService_EnrollFace_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _BiometricService_DeleteProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "biometric.proto",
}
