// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: biometric.proto

package biometricpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FraudFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FraudType     string                 `protobuf:"bytes,1,opt,name=fraud_type,json=fraudType,proto3" json:"fraud_type,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudFlag) Reset() {
	*x = FraudFlag{}
	mi := &file_biometric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudFlag) ProtoMessage() {}

func (x *FraudFlag) ProtoReflect() protoreflect.Message {
	mi := &file_biometric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudFlag.ProtoReflect.Descriptor instead.
func (*FraudFlag) Descriptor() ([]byte, []int) {
	return file_biometric_proto_rawDescGZIP(), []int{0}
}

func (x *FraudFlag) GetFraudType() string {
	if x != nil {
		return x.FraudType
	}
	return ""
}

func (x *FraudFlag) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *FraudFlag) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type VerifyPunchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameJpeg     []byte                 `protobuf:"bytes,1,opt,name=frame_jpeg,json=frameJpeg,proto3" json:"frame_jpeg,omitempty"`
	EmployeeId    string                 `protobuf:"bytes,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPunchRequest) Reset() {
	*x = VerifyPunchRequest{}
	mi := &file_biometric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPunchRequest) ProtoMessage() {}

func (x *VerifyPunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biometric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPunchRequest.ProtoReflect.Descriptor instead.
func (*VerifyPunchRequest) Descriptor() ([]byte, []int) {
	return file_biometric_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyPunchRequest) GetFrameJpeg() []byte {
	if x != nil {
		return x.FrameJpeg
	}
	return nil
}

func (x *VerifyPunchRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *VerifyPunchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type VerifyPunchResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IsLive                bool                   `protobuf:"varint,1,opt,name=is_live,json=isLive,proto3" json:"is_live,omitempty"`
	LivenessScore         float32                `protobuf:"fixed32,2,opt,name=liveness_score,json=livenessScore,proto3" json:"liveness_score,omitempty"`
	IsRecognized          bool                   `protobuf:"varint,3,opt,name=is_recognized,json=isRecognized,proto3" json:"is_recognized,omitempty"`
	RecognitionConfidence float32                `protobuf:"fixed32,4,opt,name=recognition_confidence,json=recognitionConfidence,proto3" json:"recognition_confidence,omitempty"`
	MatchedEmployeeId     string                 `protobuf:"bytes,5,opt,name=matched_employee_id,json=matchedEmployeeId,proto3" json:"matched_employee_id,omitempty"`
	FraudFlags            []*FraudFlag           `protobuf:"bytes,6,rep,name=fraud_flags,json=fraudFlags,proto3" json:"fraud_flags,omitempty"`
	Embedding             []byte                 `protobuf:"bytes,7,opt,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VerifyPunchResponse) Reset() {
	*x = VerifyPunchResponse{}
	mi := &file_biometric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPunchResponse) ProtoMessage() {}

func (x *VerifyPunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_biometric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPunchResponse.ProtoReflect.Descriptor instead.
func (*VerifyPunchResponse) Descriptor() ([]byte, []int) {
	return file_biometric_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyPunchResponse) GetIsLive() bool {
	if x != nil {
		return x.IsLive
	}
	return false
}

func (x *VerifyPunchResponse) GetLivenessScore() float32 {
	if x != nil {
		return x.LivenessScore
	}
	return 0
}

func (x *VerifyPunchResponse) GetIsRecognized() bool {
	if x != nil {
		return x.IsRecognized
	}
	return false
}

func (x *VerifyPunchResponse) GetRecognitionConfidence() float32 {
	if x != nil {
		return x.RecognitionConfidence
	}
	return 0
}

func (x *VerifyPunchResponse) GetMatchedEmployeeId() string {
	if x != nil {
		return x.MatchedEmployeeId
	}
	return ""
}

func (x *VerifyPunchResponse) GetFraudFlags() []*FraudFlag {
	if x != nil {
		return x.FraudFlags
	}
	return nil
}

func (x *VerifyPunchResponse) GetEmbedding() []byte {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type EnrollFaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameJpeg     []byte                 `protobuf:"bytes,1,opt,name=frame_jpeg,json=frameJpeg,proto3" json:"frame_jpeg,omitempty"`
	EmployeeId    string                 `protobuf:"bytes,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Angle         string                 `protobuf:"bytes,4,opt,name=angle,proto3" json:"angle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollFaceRequest) Reset() {
	*x = EnrollFaceRequest{}
	mi := &file_biometric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollFaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollFaceRequest) ProtoMessage() {}

func (x *EnrollFaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biometric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollFaceRequest.ProtoReflect.Descriptor instead.
func (*EnrollFaceRequest) Descriptor() ([]byte, []int) {
	return file_biometric_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollFaceRequest) GetFrameJpeg() []byte {
	if x != nil {
		return x.FrameJpeg
	}
	return nil
}

func (x *EnrollFaceRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *EnrollFaceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EnrollFaceRequest) GetAngle() string {
	if x != nil {
		return x.Angle
	}
	return ""
}

type EnrollFaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLive        bool                   `protobuf:"varint,1,opt,name=is_live,json=isLive,proto3" json:"is_live,omitempty"`
	LivenessScore float32                `protobuf:"fixed32,2,opt,name=liveness_score,json=livenessScore,proto3" json:"liveness_score,omitempty"`
	QualityScore  float32                `protobuf:"fixed32,3,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	Embedding     []byte                 `protobuf:"bytes,4,opt,name=embedding,proto3" json:"embedding,omitempty"`
	FraudFlags    []*FraudFlag           `protobuf:"bytes,5,rep,name=fraud_flags,json=fraudFlags,proto3" json:"fraud_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollFaceResponse) Reset() {
	*x = EnrollFaceResponse{}
	mi := &file_biometric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollFaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollFaceResponse) ProtoMessage() {}

func (x *EnrollFaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_biometric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollFaceResponse.ProtoReflect.Descriptor instead.
func (*EnrollFaceResponse) Descriptor() ([]byte, []int) {
	return file_biometric_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollFaceResponse) GetIsLive() bool {
	if x != nil {
		return x.IsLive
	}
	return false
}

func (x *EnrollFaceResponse) GetLivenessScore() float32 {
	if x != nil {
		return x.LivenessScore
	}
	return 0
}

func (x *EnrollFaceResponse) GetQualityScore() float32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *EnrollFaceResponse) GetEmbedding() []byte {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EnrollFaceResponse) GetFraudFlags() []*FraudFlag {
	if x != nil {
		return x.FraudFlags
	}
	return nil
}

type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    string                 `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_biometric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biometric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_biometric_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProfileRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *DeleteProfileRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_biometric_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_biometric_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_biometric_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_biometric_proto protoreflect.FileDescriptor

const file_biometric_proto_rawDesc = "" +
	"\n" +
	"\x0fbiometric.proto\x12\x19openpresence.biometric.v1\"k\n" +
	"\tFraudFlag\x12\x1d\n" +
	"\n" +
	"fraud_type\x18\x01 \x01(\tR\tfraudType\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\"q\n" +
	"\x12VerifyPunchRequest\x12\x1d\n" +
	"\n" +
	"frame_jpeg\x18\x01 \x01(\fR\tframeJpeg\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\tR\n" +
	"employeeId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\xc6\x02\n" +
	"\x13VerifyPunchResponse\x12\x17\n" +
	"\ais_live\x18\x01 \x01(\bR\x06isLive\x12%\n" +
	"\x0eliveness_score\x18\x02 \x01(\x02R\rlivenessScore\x12#\n" +
	"\ris_recognized\x18\x03 \x01(\bR\fisRecognized\x125\n" +
	"\x16recognition_confidence\x18\x04 \x01(\x02R\x15recognitionConfidence\x12.\n" +
	"\x13matched_employee_id\x18\x05 \x01(\tR\x11matchedEmployeeId\x12E\n" +
	"\vfraud_flags\x18\x06 \x03(\v2$.openpresence.biometric.v1.FraudFlagR\n" +
	"fraudFlags\x12\x1c\n" +
	"\tembedding\x18\a \x01(\fR\tembedding\"\x86\x01\n" +
	"\x11EnrollFaceRequest\x12\x1d\n" +
	"\n" +
	"frame_jpeg\x18\x01 \x01(\fR\tframeJpeg\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\tR\n" +
	"employeeId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x14\n" +
	"\x05angle\x18\x04 \x01(\tR\x05angle\"\xde\x01\n" +
	"\x12EnrollFaceResponse\x12\x17\n" +
	"\ais_live\x18\x01 \x01(\bR\x06isLive\x12%\n" +
	"\x0eliveness_score\x18\x02 \x01(\x02R\rlivenessScore\x12#\n" +
	"\rquality_score\x18\x03 \x01(\x02R\fqualityScore\x12\x1c\n" +
	"\tembedding\x18\x04 \x01(\fR\tembedding\x12E\n" +
	"\vfraud_flags\x18\x05 \x03(\v2$.openpresence.biometric.v1.FraudFlagR\n" +
	"fraudFlags\"T\n" +
	"\x14DeleteProfileRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\tR\n" +
	"employeeId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"1\n" +
	"\x15DeleteProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xdf\x02\n" +
	"\x10BiometricService\x12l\n" +
	"\vVerifyPunch\x12-.openpresence.biometric.v1.VerifyPunchRequest\x1a..openpresence.biometric.v1.VerifyPunchResponse\x12i\n" +
	"\n" +
	"EnrollFace\x12,.openpresence.biometric.v1.EnrollFaceRequest\x1a-.openpresence.biometric.v1.EnrollFaceResponse\x12r\n" +
	"\rDeleteProfile\x12/.openpresence.biometric.v1.DeleteProfileRequest\x1a0.openpresence.biometric.v1.DeleteProfileResponseBnZlgithub.com/AlexandreZanata/OpenPresence/services/attendance/internal/infrastructure/biometric/pb;biometricpbb\x06proto3"

var (
	file_biometric_proto_rawDescOnce sync.Once
	file_biometric_proto_rawDescData []byte
)

func file_biometric_proto_rawDescGZIP() []byte {
	file_biometric_proto_rawDescOnce.Do(func() {
		file_biometric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_biometric_proto_rawDesc), len(file_biometric_proto_rawDesc)))
	})
	return file_biometric_proto_rawDescData
}

var file_biometric_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_biometric_proto_goTypes = []any{
	(*FraudFlag)(nil),             // 0: openpresence.biometric.v1.FraudFlag
	(*VerifyPunchRequest)(nil),    // 1: openpresence.biometric.v1.VerifyPunchRequest
	(*VerifyPunchResponse)(nil),   // 2: openpresence.biometric.v1.VerifyPunchResponse
	(*EnrollFaceRequest)(nil),     // 3: openpresence.biometric.v1.EnrollFaceRequest
	(*EnrollFaceResponse)(nil),    // 4: openpresence.biometric.v1.EnrollFaceResponse
	(*DeleteProfileRequest)(nil),  // 5: openpresence.biometric.v1.DeleteProfileRequest
	(*DeleteProfileResponse)(nil), // 6: openpresence.biometric.v1.DeleteProfileResponse
}
var file_biometric_proto_depIdxs = []int32{
	0, // 0: openpresence.biometric.v1.VerifyPunchResponse.fraud_flags:type_name -> openpresence.biometric.v1.FraudFlag
	0, // 1: openpresence.biometric.v1.EnrollFaceResponse.fraud_flags:type_name -> openpresence.biometric.v1.FraudFlag
	1, // 2: openpresence.biometric.v1.BiometricService.VerifyPunch:input_type -> openpresence.biometric.v1.VerifyPunchRequest
	3, // 3: openpresence.biometric.v1.BiometricService.EnrollFace:input_type -> openpresence.biometric.v1.EnrollFaceRequest
	5, // 4: openpresence.biometric.v1.BiometricService.DeleteProfile:input_type -> openpresence.biometric.v1.DeleteProfileRequest
	2, // 5: openpresence.biometric.v1.BiometricService.VerifyPunch:output_type -> openpresence.biometric.v1.VerifyPunchResponse
	4, // 6: openpresence.biometric.v1.BiometricService.EnrollFace:output_type -> openpresence.biometric.v1.EnrollFaceResponse
	6, // 7: openpresence.biometric.v1.BiometricService.DeleteProfile:output_type -> openpresence.biometric.v1.DeleteProfileResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_biometric_proto_init() }
func file_biometric_proto_init() {
	if File_biometric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_biometric_proto_rawDesc), len(file_biometric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_biometric_proto_goTypes,
		DependencyIndexes: file_biometric_proto_depIdxs,
		MessageInfos:      file_biometric_proto_msgTypes,
	}.Build()
	File_biometric_proto = out.File
	file_biometric_proto_goTypes = nil
	file_biometric_proto_depIdxs = nil
}
